-- =============================================================
-- 員工座位系統 DDL（進階版：認證 + 公告 + 擬真座位）
-- 資料庫：MySQL 8.0
-- 執行方式：mysql -u root -p < 01_DDL.sql
-- =============================================================

CREATE DATABASE IF NOT EXISTS seat_system
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE seat_system;

-- -------------------------------------------------------------
-- 資料表
-- -------------------------------------------------------------

-- 樓層座位表（POS_ROW/POS_COL 用於前端擬真平面圖定位）
CREATE TABLE IF NOT EXISTS SEATING_CHART (
    FLOOR_SEAT_SEQ INT          NOT NULL AUTO_INCREMENT COMMENT '序號',
    FLOOR_NO       INT          NOT NULL COMMENT '樓層編號',
    SEAT_NO        INT          NOT NULL COMMENT '座位編號',
    POS_ROW        INT          NOT NULL DEFAULT 0 COMMENT '平面圖列座標',
    POS_COL        INT          NOT NULL DEFAULT 0 COMMENT '平面圖欄座標',
    SEAT_TYPE      VARCHAR(10)  NOT NULL DEFAULT 'NORMAL' COMMENT 'NORMAL / MANAGER',
    PRIMARY KEY (FLOOR_SEAT_SEQ),
    UNIQUE KEY UK_FLOOR_SEAT (FLOOR_NO, SEAT_NO),
    UNIQUE KEY UK_FLOOR_POS (FLOOR_NO, POS_ROW, POS_COL)
) COMMENT = '樓層座位表';

-- 員工資料（含登入角色與密碼雜湊）
CREATE TABLE IF NOT EXISTS EMPLOYEE (
    EMP_ID         CHAR(5)      NOT NULL COMMENT '員編（固定5碼）',
    NAME           VARCHAR(50)  NOT NULL COMMENT '員工姓名',
    EMAIL          VARCHAR(100) NOT NULL COMMENT '員工電子郵件',
    ROLE           VARCHAR(10)  NOT NULL DEFAULT 'EMPLOYEE' COMMENT 'ADMIN / EMPLOYEE',
    PASSWORD_HASH  VARCHAR(100) NULL COMMENT 'bcrypt 密碼雜湊',
    FLOOR_SEAT_SEQ INT          NULL COMMENT '座位資訊（NULL=未配位）',
    PRIMARY KEY (EMP_ID),
    UNIQUE KEY UK_EMP_SEAT (FLOOR_SEAT_SEQ),
    CONSTRAINT FK_EMP_SEAT FOREIGN KEY (FLOOR_SEAT_SEQ)
        REFERENCES SEATING_CHART (FLOOR_SEAT_SEQ)
) COMMENT = '員工資料';

-- 座位異動紀錄（與 EMPLOYEE 在同一交易內寫入）
CREATE TABLE IF NOT EXISTS SEAT_CHANGE_LOG (
    LOG_SEQ            BIGINT   NOT NULL AUTO_INCREMENT COMMENT '流水號',
    EMP_ID             CHAR(5)  NOT NULL COMMENT '員編',
    OLD_FLOOR_SEAT_SEQ INT      NULL COMMENT '異動前座位',
    NEW_FLOOR_SEAT_SEQ INT      NULL COMMENT '異動後座位',
    CHANGE_TIME        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '異動時間',
    PRIMARY KEY (LOG_SEQ)
) COMMENT = '座位異動紀錄';

-- 公告
CREATE TABLE IF NOT EXISTS ANNOUNCEMENT (
    ANN_SEQ     BIGINT        NOT NULL AUTO_INCREMENT COMMENT '序號',
    TITLE       VARCHAR(100)  NOT NULL COMMENT '標題',
    CONTENT     VARCHAR(1000) NOT NULL COMMENT '內容',
    CREATED_BY  CHAR(5)       NOT NULL COMMENT '發布者員編',
    CREATED_AT  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立時間',
    UPDATED_AT  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    PRIMARY KEY (ANN_SEQ)
) COMMENT = '公告';

-- 密碼重設驗證碼（驗證碼僅存雜湊）
CREATE TABLE IF NOT EXISTS PASSWORD_RESET_CODE (
    CODE_SEQ    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '序號',
    EMP_ID      CHAR(5)      NOT NULL COMMENT '員編',
    CODE_HASH   VARCHAR(100) NOT NULL COMMENT '6碼驗證碼雜湊',
    EXPIRES_AT  DATETIME     NOT NULL COMMENT '到期時間',
    ATTEMPTS    INT          NOT NULL DEFAULT 0 COMMENT '已嘗試次數',
    USED        TINYINT      NOT NULL DEFAULT 0 COMMENT '是否已使用',
    CREATED_AT  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立時間',
    PRIMARY KEY (CODE_SEQ),
    KEY IDX_RESET_EMP (EMP_ID, USED, EXPIRES_AT)
) COMMENT = '密碼重設驗證碼';

-- -------------------------------------------------------------
-- Stored Procedures
-- 交易由應用程式（Spring @Transactional）控制，SP 內不自行 COMMIT。
-- -------------------------------------------------------------

DELIMITER $$

-- 取得所有樓層
DROP PROCEDURE IF EXISTS SP_GET_FLOORS $$
CREATE PROCEDURE SP_GET_FLOORS()
BEGIN
    SELECT DISTINCT FLOOR_NO FROM SEATING_CHART ORDER BY FLOOR_NO;
END $$

-- 取得指定樓層全部座位（含座標、型別與佔用者）
DROP PROCEDURE IF EXISTS SP_GET_SEATS_BY_FLOOR $$
CREATE PROCEDURE SP_GET_SEATS_BY_FLOOR(IN p_floor_no INT)
BEGIN
    SELECT sc.FLOOR_SEAT_SEQ, sc.FLOOR_NO, sc.SEAT_NO,
           sc.POS_ROW, sc.POS_COL, sc.SEAT_TYPE,
           e.EMP_ID, e.NAME
    FROM SEATING_CHART sc
    LEFT JOIN EMPLOYEE e ON e.FLOOR_SEAT_SEQ = sc.FLOOR_SEAT_SEQ
    WHERE sc.FLOOR_NO = p_floor_no
    ORDER BY sc.POS_ROW, sc.POS_COL;
END $$

-- 取得全部員工（下拉選單用）
DROP PROCEDURE IF EXISTS SP_GET_ALL_EMPLOYEES $$
CREATE PROCEDURE SP_GET_ALL_EMPLOYEES()
BEGIN
    SELECT e.EMP_ID, e.NAME, e.EMAIL, e.FLOOR_SEAT_SEQ,
           sc.FLOOR_NO, sc.SEAT_NO
    FROM EMPLOYEE e
    LEFT JOIN SEATING_CHART sc ON sc.FLOOR_SEAT_SEQ = e.FLOOR_SEAT_SEQ
    ORDER BY e.EMP_ID;
END $$

-- 指派座位（檢查 + 更新 EMPLOYEE + 寫 LOG）
DROP PROCEDURE IF EXISTS SP_ASSIGN_SEAT $$
CREATE PROCEDURE SP_ASSIGN_SEAT(IN p_emp_id CHAR(5), IN p_floor_seat_seq INT)
BEGIN
    DECLARE v_old_seat INT     DEFAULT NULL;
    DECLARE v_occupant CHAR(5) DEFAULT NULL;

    IF NOT EXISTS (SELECT 1 FROM SEATING_CHART WHERE FLOOR_SEAT_SEQ = p_floor_seat_seq) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '座位不存在';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM EMPLOYEE WHERE EMP_ID = p_emp_id) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '員工不存在';
    END IF;

    SELECT EMP_ID INTO v_occupant FROM EMPLOYEE
    WHERE FLOOR_SEAT_SEQ = p_floor_seat_seq FOR UPDATE;
    IF v_occupant IS NOT NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '座位已被佔用';
    END IF;

    SELECT FLOOR_SEAT_SEQ INTO v_old_seat FROM EMPLOYEE WHERE EMP_ID = p_emp_id;
    UPDATE EMPLOYEE SET FLOOR_SEAT_SEQ = p_floor_seat_seq WHERE EMP_ID = p_emp_id;
    INSERT INTO SEAT_CHANGE_LOG (EMP_ID, OLD_FLOOR_SEAT_SEQ, NEW_FLOOR_SEAT_SEQ)
    VALUES (p_emp_id, v_old_seat, p_floor_seat_seq);
END $$

-- 清除座位
DROP PROCEDURE IF EXISTS SP_CLEAR_SEAT $$
CREATE PROCEDURE SP_CLEAR_SEAT(IN p_floor_seat_seq INT)
BEGIN
    DECLARE v_emp_id CHAR(5) DEFAULT NULL;
    SELECT EMP_ID INTO v_emp_id FROM EMPLOYEE
    WHERE FLOOR_SEAT_SEQ = p_floor_seat_seq FOR UPDATE;
    IF v_emp_id IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '該座位目前無人佔用';
    END IF;
    UPDATE EMPLOYEE SET FLOOR_SEAT_SEQ = NULL WHERE EMP_ID = v_emp_id;
    INSERT INTO SEAT_CHANGE_LOG (EMP_ID, OLD_FLOOR_SEAT_SEQ, NEW_FLOOR_SEAT_SEQ)
    VALUES (v_emp_id, p_floor_seat_seq, NULL);
END $$

-- 登入資訊（含密碼雜湊與角色）
DROP PROCEDURE IF EXISTS SP_GET_LOGIN_INFO $$
CREATE PROCEDURE SP_GET_LOGIN_INFO(IN p_emp_id CHAR(5))
BEGIN
    SELECT EMP_ID, NAME, EMAIL, ROLE, PASSWORD_HASH
    FROM EMPLOYEE WHERE EMP_ID = p_emp_id;
END $$

-- 依員編查基本資料（忘記密碼用）
DROP PROCEDURE IF EXISTS SP_GET_EMPLOYEE_BY_ID $$
CREATE PROCEDURE SP_GET_EMPLOYEE_BY_ID(IN p_emp_id CHAR(5))
BEGIN
    SELECT EMP_ID, NAME, EMAIL, ROLE FROM EMPLOYEE WHERE EMP_ID = p_emp_id;
END $$

-- 更新密碼
DROP PROCEDURE IF EXISTS SP_UPDATE_PASSWORD $$
CREATE PROCEDURE SP_UPDATE_PASSWORD(IN p_emp_id CHAR(5), IN p_hash VARCHAR(100))
BEGIN
    UPDATE EMPLOYEE SET PASSWORD_HASH = p_hash WHERE EMP_ID = p_emp_id;
    IF ROW_COUNT() = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '員工不存在';
    END IF;
END $$

-- 公告：查全部
DROP PROCEDURE IF EXISTS SP_GET_ANNOUNCEMENTS $$
CREATE PROCEDURE SP_GET_ANNOUNCEMENTS()
BEGIN
    SELECT a.ANN_SEQ, a.TITLE, a.CONTENT, a.CREATED_BY, e.NAME AS CREATED_BY_NAME,
           a.CREATED_AT, a.UPDATED_AT
    FROM ANNOUNCEMENT a
    LEFT JOIN EMPLOYEE e ON e.EMP_ID = a.CREATED_BY
    ORDER BY a.CREATED_AT DESC;
END $$

-- 公告：新增
DROP PROCEDURE IF EXISTS SP_CREATE_ANNOUNCEMENT $$
CREATE PROCEDURE SP_CREATE_ANNOUNCEMENT(IN p_title VARCHAR(100), IN p_content VARCHAR(1000), IN p_created_by CHAR(5))
BEGIN
    INSERT INTO ANNOUNCEMENT (TITLE, CONTENT, CREATED_BY)
    VALUES (p_title, p_content, p_created_by);
    SELECT LAST_INSERT_ID() AS ANN_SEQ;
END $$

-- 公告：編輯
DROP PROCEDURE IF EXISTS SP_UPDATE_ANNOUNCEMENT $$
CREATE PROCEDURE SP_UPDATE_ANNOUNCEMENT(IN p_ann_seq BIGINT, IN p_title VARCHAR(100), IN p_content VARCHAR(1000))
BEGIN
    UPDATE ANNOUNCEMENT SET TITLE = p_title, CONTENT = p_content WHERE ANN_SEQ = p_ann_seq;
    IF ROW_COUNT() = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '公告不存在';
    END IF;
END $$

-- 公告：刪除
DROP PROCEDURE IF EXISTS SP_DELETE_ANNOUNCEMENT $$
CREATE PROCEDURE SP_DELETE_ANNOUNCEMENT(IN p_ann_seq BIGINT)
BEGIN
    DELETE FROM ANNOUNCEMENT WHERE ANN_SEQ = p_ann_seq;
    IF ROW_COUNT() = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '公告不存在';
    END IF;
END $$

-- 驗證碼：建立（先把該員工舊的未使用碼作廢，確保單一有效碼）
DROP PROCEDURE IF EXISTS SP_CREATE_RESET_CODE $$
CREATE PROCEDURE SP_CREATE_RESET_CODE(IN p_emp_id CHAR(5), IN p_code_hash VARCHAR(100), IN p_expires_at DATETIME)
BEGIN
    UPDATE PASSWORD_RESET_CODE SET USED = 1 WHERE EMP_ID = p_emp_id AND USED = 0;
    INSERT INTO PASSWORD_RESET_CODE (EMP_ID, CODE_HASH, EXPIRES_AT)
    VALUES (p_emp_id, p_code_hash, p_expires_at);
END $$

-- 驗證碼：取得目前有效碼（未使用、未過期，最新一筆）
DROP PROCEDURE IF EXISTS SP_GET_ACTIVE_RESET_CODE $$
CREATE PROCEDURE SP_GET_ACTIVE_RESET_CODE(IN p_emp_id CHAR(5))
BEGIN
    SELECT CODE_SEQ, EMP_ID, CODE_HASH, EXPIRES_AT, ATTEMPTS, USED
    FROM PASSWORD_RESET_CODE
    WHERE EMP_ID = p_emp_id AND USED = 0
    ORDER BY CREATED_AT DESC
    LIMIT 1;
END $$

-- 驗證碼：標記已使用
DROP PROCEDURE IF EXISTS SP_MARK_RESET_CODE_USED $$
CREATE PROCEDURE SP_MARK_RESET_CODE_USED(IN p_code_seq BIGINT)
BEGIN
    UPDATE PASSWORD_RESET_CODE SET USED = 1 WHERE CODE_SEQ = p_code_seq;
END $$

-- 驗證碼：嘗試次數 +1
DROP PROCEDURE IF EXISTS SP_INCREMENT_RESET_ATTEMPTS $$
CREATE PROCEDURE SP_INCREMENT_RESET_ATTEMPTS(IN p_code_seq BIGINT)
BEGIN
    UPDATE PASSWORD_RESET_CODE SET ATTEMPTS = ATTEMPTS + 1 WHERE CODE_SEQ = p_code_seq;
END $$

DELIMITER ;
