-- 員工座位系統 DML（進階版：含角色/密碼雜湊/擬真座位/公告）
-- 執行：mysql -u root -p < 02_DML.sql （需先跑 01_DDL.sql）
USE seat_system;

-- 樓層座位（含擬真平面座標）
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,1,1,1,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,2,1,2,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,3,1,4,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,4,1,5,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,5,1,7,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,6,1,8,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,7,2,1,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,8,2,2,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,9,2,4,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,10,2,5,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,11,2,7,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,12,2,8,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,13,4,1,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,14,4,2,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,15,4,4,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,16,4,5,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,17,4,7,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,18,4,8,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,19,5,1,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,20,5,2,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,21,5,4,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,22,5,5,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,23,5,7,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (10,24,5,8,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,1,1,1,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,2,1,2,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,3,1,3,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,4,1,4,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,5,1,5,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,6,1,6,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,7,1,7,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,8,1,8,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,9,1,9,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,10,1,10,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,11,5,1,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,12,5,2,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,13,5,3,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,14,5,4,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,15,5,5,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,16,5,6,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,17,5,7,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,18,5,8,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,19,5,9,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (11,20,5,10,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,1,1,1,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,2,1,2,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,3,1,3,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,4,1,4,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,5,2,1,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,6,2,2,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,7,2,3,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,8,2,4,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,9,3,1,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,10,3,2,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,11,3,3,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,12,3,4,'NORMAL');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,13,1,6,'MANAGER');
INSERT INTO SEATING_CHART (FLOOR_NO,SEAT_NO,POS_ROW,POS_COL,SEAT_TYPE) VALUES (12,14,3,6,'MANAGER');

-- 員工（密碼為 bcrypt 雜湊；明碼=出生年月日YYYYMMDD+身分證後4碼，詳見 docs/seed-passwords.md）
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('A0001','王小明','ming.wang@example.com','ADMIN','$2b$12$KynRlvxysr8lXWpu2RCmfOsT1oR5IiMDEFEA0XCSTGz3zxpy9bB2m',(SELECT FLOOR_SEAT_SEQ FROM SEATING_CHART WHERE FLOOR_NO=10 AND SEAT_NO=1));
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('A0002','李小華','hua.li@example.com','EMPLOYEE','$2b$12$OxATVLVvygY8J0oOcABncuvt7fkp4idddVt/0Evd.bG0OPfRPISgS',(SELECT FLOOR_SEAT_SEQ FROM SEATING_CHART WHERE FLOOR_NO=10 AND SEAT_NO=3));
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('A0003','張大同','datong.chang@example.com','EMPLOYEE','$2b$12$yEAwnIIzTY1i4YNttIbar.YoMHQ5/0/lW2MteLuiyYkVCqBQpVOBa',(SELECT FLOOR_SEAT_SEQ FROM SEATING_CHART WHERE FLOOR_NO=10 AND SEAT_NO=7));
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('A0004','陳美玲','meiling.chen@example.com','EMPLOYEE','$2b$12$qGNWAWs7Y2CouhuGkJ79jOlNJ4cBmhz3U93BqhiekQKxS0uRx41j6',(SELECT FLOOR_SEAT_SEQ FROM SEATING_CHART WHERE FLOOR_NO=11 AND SEAT_NO=2));
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('A0005','林志偉','chihwei.lin@example.com','EMPLOYEE','$2b$12$0XTZs08VFb7W2Q9Um6FGTeW2uldUWs8x3V/iNcAOMZM.uab21MP8q',(SELECT FLOOR_SEAT_SEQ FROM SEATING_CHART WHERE FLOOR_NO=11 AND SEAT_NO=5));
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('A0006','黃淑芬','shufen.huang@example.com','EMPLOYEE','$2b$12$M9lzMUVyfy.HU3wD7Ysir.D7Pj.jIkUO4ynONl0NKL0YNuvIQs8l2',(SELECT FLOOR_SEAT_SEQ FROM SEATING_CHART WHERE FLOOR_NO=12 AND SEAT_NO=1));
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('A0007','吳建宏','chienhung.wu@example.com','EMPLOYEE','$2b$12$lkabn4Uyco2z/M46fnJjvuT.fOqZgmYSJhyXq4STzZ/twWcCM1GEK',(SELECT FLOOR_SEAT_SEQ FROM SEATING_CHART WHERE FLOOR_NO=12 AND SEAT_NO=13));
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('A0008','劉雅婷','yating.liu@example.com','EMPLOYEE','$2b$12$o8ggpCjLZQLGSzUxz7cob./h6XkPIGrUXj4yMcCYa1ZfwLc1jCAqa',NULL);
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('A0009','蔡明哲','mingche.tsai@example.com','EMPLOYEE','$2b$12$bPC6ct1cvVYQcbIm.96EWeMJDiavLCHyjHHgihMunKfYjVQ5niipm',NULL);
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('A0010','鄭佳蓉','chiajung.cheng@example.com','EMPLOYEE','$2b$12$SZskx7pyI/EurCR5lKnDqeH9bqEEoERmRVn3sbMs7T9iWr6ygOJhm',NULL);
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('B0001','謝俊傑','chunchieh.hsieh@example.com','EMPLOYEE','$2b$12$O2vNb8BYgQK3bsprvFAsHO0C4vVnn0VVmDeTHYRSi2a7E.aWGWhRu',NULL);
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('B0002','許芳瑜','fangyu.hsu@example.com','EMPLOYEE','$2b$12$3jFBuzX5NYspz8Iu/WoCB.OQ8YUUnAHVQGdnAwWSuls170qw.T5j6',NULL);
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('B0003','楊宗翰','tsunghan.yang@example.com','EMPLOYEE','$2b$12$YUyOFWV2XhqWLBV.2WbJM.UiGVgSlpGyjSHlHS1SlEWDMyJWHwR4G',NULL);
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('B0004','蕭惠君','huichun.hsiao@example.com','EMPLOYEE','$2b$12$zUOcEA89H4lS9Wwrc3vuYOfh38X4U4zDj7XvGSixsg67mxCTipZqW',NULL);
INSERT INTO EMPLOYEE (EMP_ID,NAME,EMAIL,ROLE,PASSWORD_HASH,FLOOR_SEAT_SEQ) VALUES ('B0005','潘冠宇','kuanyu.pan@example.com','EMPLOYEE','$2b$12$Qeju0RQnL4nSivyYj8JYkek1K3UDdgshkHHyQrFJCe1GKJIlF8QI.',NULL);

-- 公告種子
INSERT INTO ANNOUNCEMENT (TITLE,CONTENT,CREATED_BY) VALUES ('系統上線公告','員工座位安排系統正式上線，請各位同仁多加利用。','A0001');
INSERT INTO ANNOUNCEMENT (TITLE,CONTENT,CREATED_BY) VALUES ('座位調整通知','本週五前完成 12 樓主管區座位確認，如有問題請洽人資。','A0001');
